
# Update this file after adding/removing/renaming a target by running the script from gluon dir
# `make list-targets BROKEN=0 GLUON_DEPRECATED=upgrade GLUON_SITEDIR="../"| ../actions/generate-actions.py > ../.github/workflows/build-gluon.yml`

name: Build Gluon
on:
  push:
    tags:
      - 2021.*
      - 2022.*
      - 2023.*
jobs:
  build_firmware:
    strategy:
      fail-fast: false
      matrix:
        target: [ath79-generic, ath79-nand, ath79-mikrotik, bcm27xx-bcm2708, bcm27xx-bcm2709, ipq40xx-generic, ipq40xx-mikrotik, ipq806x-generic, lantiq-xrx200, lantiq-xway, mediatek-mt7622, mpc85xx-p1010, mpc85xx-p1020, ramips-mt7620, ramips-mt7621, ramips-mt76x8, rockchip-armv8, sunxi-cortexa7, x86-generic, x86-geode, x86-legacy, x86-64, bcm27xx-bcm2710, mvebu-cortexa9]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Install Dependencies
        run: sudo actions/install-dependencies.sh
      - name: Build
        run: actions/run-build.sh ${{matrix.target}}
      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.VERSION }}_${{matrix.target}}_output
          path: gluon/output

