name: Create new release
on: workflow_dispatch
jobs:
  release:
    name: Download release
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
        with:
          repository: ffsh/firmware-collector
      - name: Checkout
      - name: Install python deps
        run: pip3 install -r requirements.txt
      - name: Update DB
        run: ./cli.py --update
      - name: Download files
        run: ./cli.py --download ${{ steps.get_version.outputs.VERSION }}
      - name: Store files
        run: ./cli.py --
