
# Update this file after adding/removing/renaming a target by running the script from gluon dir
# `make list-targets BROKEN=0 GLUON_DEPRECATED=upgrade GLUON_SITEDIR="../"| ../actions/generate-actions.py > ../.github/workflows/build-gluon.yml`

name: Build Gluon
on:
  push:
    tags:
      - 2021.*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  download-release:
    name: Download release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ffsh/firmware-collector
      - name: Checkout
      - name: Install python deps
        run: pip3 install -r requirements.txt
      - name: Update DB
        run: ./cli.py --update
        run: commit db change
      - name: Download files
        run: ./cli.py --download $Version

  unpack-release:
    name: Unpack release
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v2
        with:
          repository: 'ffsh/firmware-collector'
      - name: 
  